
name : push

on :

  workflow_call :
    inputs :
      matrix :
        required : true
        type : string
jobs :

  fast :
    strategy :
      fail-fast : false
      matrix :
        version : ${{ toJson( inputs.matrix ) }}
    runs-on : ubuntu-latest
    steps :
      - run : echo ${{ matrix.version }}
