
name : exp

on :

  workflow_call :
    inputs :
      matrix :
        required : true
        type : string
      modules :
        required : true
        type : string

jobs:
  wait_for_modules :
    runs-on : ubuntu-latest
    env:
      INPUT_W : ${{ inputs.modules }}
    steps :
      - run: echo -e "$INPUT_W"
      - run: echo -e "${{ inputs.modules }}"
      - run: |
        val=$(sed 's/\s/\n/g' <<< $INPUT_W)
        export INPUT_B=$val
        echo -e "$val"
      - run: echo "$INPUT_B"
      - name : Waiting ...
        uses : willgarcia/workflow-wait-action@main
        with :
          timeout : 21600
          interval : 10
          initial_delay : 10
          workflows : $INPUT_W

  check :
    needs : wait_for_modules
    strategy :
      matrix : ${{ fromJson( inputs.matrix ) }}
    outputs :
      has_succeeded_runs : ${{ steps.success.outputs.success }}
    runs-on : ubuntu-latest
    steps :
      - run: echo "${{ inputs.matrix }}"
      - name : Check workflow run status
        id : check_ci
        uses :  LASER-Yi/workflow-status@v0.1.0
        with :
          token : ${{ secrets.GITHUB_TOKEN }}
          workflow : ${{ matrix.modules }}.yml
          event : push
          branch : alpha
      - name : Check failure conclusion
        if : ${{ steps.check_ci.outputs.conclusion == 'failure' }}
        run : exit 1
      - name : Check cancelled conclusion
        if : ${{ steps.check_ci.outputs.conclusion == 'cancelled' }}
        run : exit 1
      - name : Check success conclusion and setup output
        if : ${{ steps.check_ci.outputs.conclusion == 'success' }}
        id : success
        run: echo "::set-output name=success::true"

