
name : exp

on :

  workflow_call :
    inputs :
      matrix :
        required : true
        type : string

jobs:
  exp :
    runs-on : ubuntu-latest
    strategy:
      matrix : ${{ fromJson( inputs.matrix ) }}
    steps :
      - run: echo ${{ matrix.modules }}
      - run: echo ${{ join( fromJson( inputs.matrix ).modules )}}

