
name : exp

on :

  workflow_call :
    inputs :
      matrix :
        required : true
        type : string

jobs:
  exp :
    runs-on : ubuntu-latest
    steps :
      - run: echo ${{ inputs.matrix }}
      - run: echo "${{ toJson( inputs.matrix ) }}"

