
name : push

on :

  workflow_call :
    inputs :
      matrix :
        required : true
        type : string
jobs :

  fast :
    if : ${{ inputs.matrix == 'single' }}
    strategy :
      fail-fast : false
      matrix :
        version : [ 14.x ]
    runs-on : ubuntu-latest
    steps :
      - run : echo ${{ matrix.version }}

  not_fast :
    if : ${{ inputs.matrix != 'single' }}
    strategy :
      fail-fast : false
      matrix :
        version : [ 14.x, 15.x, 16.x ]
    runs-on : ubuntu-latest
    steps :
      - run : echo ${{ matrix.version }}
