
name : exp

on :

  workflow_call :
    inputs :
      matrix :
        required : true
        type : string

jobs:
  exp :
    runs-on : ubuntu-latest
    steps :
      - echo ${{ github.event.inputs.matrix }}"
      - echo "${{ toJson( github.event.inputs.matrix ) }}"

