
name : runs_clean

on :
  workflow_dispatch :
    inputs :
      repo :
        description : 'repo'
        required : true
      days :
        description : 'Older than number of days.'
        required : true
        type : number
        default : 0
      save :
        description : 'Save min runs.'
        required : true
        type : number
        default : 0
      workflow_id :
        description : 'Workflow id or filename.'
        required : false
        default : ""
      branch :
        description : 'Branch.'
        required : true
        default : master

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          repo: dmvict/${{ inputs.repo }}
          branch : ${{ inputs.branch }}
          # run_conclusions: ${{ github.event.inputs.conclusion }}
          save_period: ${{ inputs.days }}
          save_min_runs_number: ${{ inputs.days }}

