name : exp

on :
  push :
    branches : [ master ]

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses : dmvict/wretry.action@js_action
        with:
          action: dmvict/test.action@multiline_option
          with: |
            multiline: |
              one
              two
            string: |
          attempt_limit: 3
          attempt_delay: 2000
  failure :
    runs-on : ubuntu-latest
    steps :
      - uses : Wandalen/wretry.action@js_action
        with:
          action: dmvict/test.action@multiline_option
          with: |
            multiline: |
              one
              two
            string: |
          attempt_limit: 3
          attempt_delay: 2000
