name : exp

on:
  workflow_dispatch

jobs:
  update-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git
        env:
          USERNAME: dmvict
        run: |
          git config user.name ${{ env.USERNAME }}
          git config user.email dm.vict.kr@gmail.com
          git remote set-url origin https://${{ env.USERNAME }}:${{ github.token }}@github.com/${{ github.repository }}.git

      - name: Commit updates
        run: |
          git add .
          git commit --allow-empty -m "test push"
          git push --force

# on :
#   push :
#     branches : [ master ]
#     tags: '**'
#
# jobs:
#   success :
#     runs-on : ubuntu-latest
#     steps :
#       - uses : dmvict/wretry.action@master
#         with:
#           command: echo foo
  # failure :
  #   runs-on : ubuntu-latest
  #   steps :
  #     - uses : Wandalen/wretry.action@js_action
  #       with:
  #         action: dmvict/test.action@multiline_option
  #         with: |
  #           multiline: |
  #             one
  #             two
  #           string: |
  #         attempt_limit: 3
  #         attempt_delay: 2000
