
name : push2

# on :
#   push :
#     branches : [ alpha ]
on : push

jobs:
  job1:
    runs-on: windows-latest
    # outputs:
    #   output1: ${{ steps.step.outputs.outputs }}
    #   output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: command
        run: |
          echo $(pwd)
          echo hello
        shell: bash
      - id: action
        uses: Wandalen/wretry.action@master
        with:
          attempt_limit: 3
          command: |
            echo $(pwd)
            echo hello

      # - id: step
      #   uses: dmvict/wretry.action@alternative_master
      #   with:
      #     attempt_limit: 3
      #     command: echo "test=hello" >> "$GITHUB_OUTPUT"
      # - id: step2
      #   uses: dmvict/test.action@master
      #   with:
      #     any: 3

  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - env:
  #         OUTPUT1: ${{ fromJSON( needs.job1.outputs.output1 ).test }}
  #         OUTPUT2: ${{needs.job1.outputs.output1}}
  #       run: echo "$OUTPUT1 $OUTPUT2"
