
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      # - uses: Wandalen/wretry.action@v3
      - uses: dmvict/wretry.action@alt
        with:
          retry_condition: github.event_name == 'push'
          action: dmvict/test.action@v0.0.2
          with: |
            value: 0
          attempt_limit: 4
          attempt_delay: 3000
