
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses: dmvict/wretry.action@alt
        env:
          TEST: true
        with:
          action: dmvict/test.action@conditions
          with: |
            value: 1
      - run: exit 1
