
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses: actions/checkout@v4
        with:
          ref: alt
      - uses: Wandalen/wretry.action@v1.4.5
        with:
          command: |
            if [[ $HOME == "/home/github" ]] ; then
              echo github
            else
              echo nongithub
            fi
          attempt_limit: 3
          attempt_delay: 2000
