
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    env:
      TEST: false
    steps :
      - uses: dmvict/wretry.action@alt
        with:
          action: dmvict/test.action@conditions
          with: |
            value: 1
