
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses: actions/checkout@v4
        with:
          ref: alt
      - uses: Wandalen/wretry.action@v1.4.4
        with:
          action: dmvict/test.action@v0.0.2
          with: |
            value: 2
          attempt_limit: 3
          attempt_delay: 2000
