
name : push2

# on :
#   push :
#     branches : [ alpha ]
on : push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step
        uses: Wandalen/wretry.action@v1.0.36
        with:
          attempt_limit: 3
          action: dmvict/test.action@master
      - id: step2
        uses: dmvict/test.action@master
        with:
          any: 3

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
