
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v4
      - uses: 'dmvict/wretry.action/main@exp'
        with:
          action: ./.github/actions
          attempt_limit: 4
          attempt_delay: 1000
