
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - name: test
        uses: dmvict/wretry.action@exp
        with:
          action: dmvict/test.action@post_without_default_input
          with: |
            value: 0
            post_value: 1
          attempt_limit: 4
          attempt_delay: 10000
