
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - run: exit 0
      - uses: dmvict/test.action@conditions
        with:
          value: 1
      - run: exit 0
