
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - name: main
        uses: Wandalen/wretry.action@master
        with:
          action: dmvict/test.action@alt
          with: |
            multiline: ${{ secrets.MULTILINE }}
            singleline: single
            true_v: true
          attempt_limit: 4
          attempt_delay: 3000
      - name: command
        run: echo -en "${{ toJSON( steps.mmmm.outputs ) }}"

