
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      # - uses: Wandalen/wretry.action@v3
      - uses: dmvict/wretry.action@alt
        with:
          retry_condition: github.ref_name == 'main'
          command: exit 1
          attempt_limit: 4
          attempt_delay: 3000
