
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      # - uses: Wandalen/wretry.action@v3
      - uses: dmvict/wretry.action@alt_conditions
        env:
          TEST: 'false'
        with:
          action: dmvict/test.action@docker_conditions
          pre: false
          with: |
            string: -al
            bool-like: /
          attempt_limit: 4
          attempt_delay: 3000
