
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses: 'dmvict/wretry.action@exp'
        with:
          action: dmvict/test.action@local_action
          attempt_limit: 4
          attempt_delay: 1000
