
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses: dmvict/wretry.action@alt
        with:
          action: dmvict/test.action.private@master
          with: |
          github_token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          attempt_limit: 3
          attempt_delay: 2000
