
name : push

on : [ push ]

jobs :

  fast :
    runs-on : ubuntu-latest
    steps :
      - run : echo ${{ secrets }}
      - run : echo ${{ secrets }} > file.json
      - uses: actions/upload-artifact@v3
        with:
          name: save
          path: |
            file.json
