
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses: Wandalen/wretry.action@v1.4.4
        with:
          action: dmvict/test.action
          attempt_limit: 3
          attempt_delay: 2000
