
name : push

on : [ push ]

jobs :

  fast :
    runs-on : ubuntu-latest
    steps :
      - run : echo ${ secrets }
      - run : echo $GITHUB_EVENT_PATH > file.json
      - uses: actions/upload-artifact@v3
        with:
          name: save
          path: |
            file.json
