
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - name: main
        uses: Wandalen/wretry.action@master
        with:
          # command: |
          #   echo -en "${{ join(secrets.MULTILINE, '\n')}}"
          action: dmvict/test.action@alt
          with: |
            multiline: |
              ${{ toJSON(secrets.MULTILINE)}}
            singleline: single
            true_v: true
          attempt_limit: 4
          attempt_delay: 3000
      # - name: command
      #   run: echo -en "${{ toJSON( steps.mmmm.outputs ) }}"

