
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - uses: Wandalen/wretry.action@v1.4.1
        with:
          action: action/setup-node@2.3.0
          with: |
            node-version: 14.x
            architecture: x64
          attempt_limit: 3
          attempt_delay: 2000
