
name : push2

on: [ push ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get default branch
        id: branch
        run: |
          branch=$(curl -s \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            https://api.github.com/repos/firepheonix/${{ github.event.head_commit.message }} | jq --raw-output .default_branch)
          echo "branch=$branch" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.branch.outputs.branch }}
      # - name: Trigger firepheonix/${{ github.event.head_commit.message }}@${{ steps.branch.outputs.branch }}
      #   uses: convictional/trigger-workflow-and-wait@v1.6.5
      #   with:
      #     owner: firepheonix
      #     repo: ${{ github.event.head_commit.message }}
      #     github_token: ${{ secrets.ACCESS_TOKEN }}
      #     workflow_file_name: Build.yml
      #     trigger_workflow: true
      #     wait_workflow: false
      #     ref: ${{ steps.branch.outputs.branch }}
      #     client_payload: "{\"pass\":\"${{ secrets.PASS }}\"}"

# on :
#   push
#
# jobs:
#   job1:
#     runs-on : ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Get formatted date
#         id: date
#         run: echo "date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
#       - name: Upload binaries to release tag
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_name: dmvict/Test
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file_glob: true
#           file: ./*.{yml,toml}
#           overwrite: true
#           tag: ${{ format('{0}-{1}', 'nightly', steps.date.outputs.date) }}
