
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      # - uses: Wandalen/wretry.action@v3
      - uses: dmvict/wretry.action@alt
        env:
          TEST: 'true'
        with:
          action: dmvict/test.action@docker_conditions
          with: |
            string: foo
            bool-like: false
          attempt_limit: 4
          attempt_delay: 3000
