
name : push1

# on : push
on :
  workflow_dispatch :
    inputs :
      value :
        description : 'repo'
        required : true
      post_value :
        description : 'repo'
        required : true

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - name: test
        uses: Wandalen/wretry.action@v3.5.0
        with:
          action: dmvict/test.action@post_without_default_input
          with: |
            value: ${{ inputs.value }}
            post_value: ${{ inputs.post_value }}
          attempt_limit: 4
          attempt_delay: 10000
