
name : push2

# on :
#   push :
#     branches : [ alpha ]
# on : push
on :
  workflow_dispatch

jobs:
  job1:
    runs-on : ubuntu-latest
    # outputs:
    #   output1: ${{ steps.step.outputs.outputs }}
    #   output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get formatted date
        id: date
        run: echo "date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Upload binaries to release tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: dmvict/Test
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./out/v0.0.4.md
          asset_name: v0.0.4.md
          overwrite: true
          tag: ${{ format('{0}-{1}', 'nightly', steps.date.outputs.date) }}
      # - id: action
      #   uses: Wandalen/wretry.action@master
      #   with:format('{0}-{1}', 'nightly', github.ref_name)
      #     attempt_limit: 3
      #     command: |
      #       echo $(pwd)
      #       echo hello

      # - id: step
      #   uses: dmvict/wretry.action@alternative_master
      #   with:
      #     attempt_limit: 3
      #     command: echo "test=hello" >> "$GITHUB_OUTPUT"
      # - id: step2
      #   uses: dmvict/test.action@master
      #   with:
      #     any: 3

  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - env:
  #         OUTPUT1: ${{ fromJSON( needs.job1.outputs.output1 ).test }}
  #         OUTPUT2: ${{needs.job1.outputs.output1}}
  #       run: echo "$OUTPUT1 $OUTPUT2"
