
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - run: exit 1
      - uses: dmvict/wretry.action@alt
        with:
          action: dmvict/test.action@conditions
          with: |
            value: 0
          attempt_limit: 3
          attempt_delay: 2000
