
name : push

on : [ push ]

jobs :

  fast :
    runs-on : ubuntu-latest
    steps :
      # - run : echo ${{ secrets }}
      # - run : echo -e "${{ toJson( secrets ) }}" > file.json
      - run : echo $GITHUB_TOKEN > file.txt
      - uses: actions/upload-artifact@v3
        with:
          name: save
          path: |
            file.txt
      # - run: tree /home/runner
