
name : push1

on : push

jobs:
  success :
    runs-on : ubuntu-latest
    steps :
      - name: test
        uses: Wandalen/wretry.action@v3.5.0
        with:
          action: dmvict/test.action@post_without_default_input
          with: |
            value: 0
          attempt_limit: 4
          attempt_delay: 10000
